version: 2.1

orbs:
  ven: vendrive/ven@<<pipeline.parameters.dev-orb-version>>
  orb-tools: circleci/orb-tools@10.0
  bats: circleci/bats@1.0
  shellcheck: circleci/shellcheck@2.0

# Pipeline Parameters
parameters:
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

jobs:
  integration-test:
    executor: ven/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '40:cb:ca:da:18:5e:a7:f8:29:2b:c5:3c:ed:0f:22:95'
      - ven/install

workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires: [orb-tools/lint]
      - orb-tools/publish-dev:
          orb-name: vendrive/ven
          context: orb-publishing
          requires: [orb-tools/pack]
      - integration-test:
          requires: [orb-tools/publish-dev]
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb-name: vendrive/ven
          context: orb-publishing
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires: [integration-test]

