description: >
  This is a sample executor using Docker and Node.
docker:
  - image: 'cimg/go:<<parameters.tag>>'
parameters:
  tag:
    default: '1.16-node'
    description: >
      Pick a specific circleci/go image variant:
      https://hub.docker.com/r/cimg/go/tags
    type: string
